version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: flask run --host=0.0.0.0
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      SECRET_KEY: dev_key
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false

volumes:
  pgdata:
  jenkins_home:
