services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    # Мы закомментировали эту строку, чтобы Docker использовал команду
    # `CMD` из нашего Dockerfile (которая запускает Gunicorn).
    # command: flask run --host=0.0.0.0
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      SECRET_KEY: dev_key
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
volumes:
  pgdata: