global:
  scrape_interval: 15s  # Собирать метрики каждые 15 секунд

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['35.228.65.138:8080']  # Замените на IP вашей новой ВМ, где работает cAdvisor
