apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-script
  namespace: blog-dev
data:
  backup.sh: |
    #!/bin/bash
    set -e
    
    # Переменные окружения
    BACKUP_DIR="/backups"
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    BACKUP_FILE="blog_backup_${TIMESTAMP}.sql"
    
    echo "🗄️ Начинаем резервное копирование PostgreSQL..."
    
    # Создаем резервную копию
    pg_dump -h postgres-service -U postgres -d blog > "${BACKUP_DIR}/${BACKUP_FILE}"
    
    # Проверяем, что файл создан
    if [ -f "${BACKUP_DIR}/${BACKUP_FILE}" ]; then
        echo "✅ Резервная копия создана: ${BACKUP_FILE}"
        
        # Сжимаем файл для экономии места
        gzip "${BACKUP_DIR}/${BACKUP_FILE}"
        echo "✅ Файл сжат: ${BACKUP_FILE}.gz"
        
        # Удаляем старые резервные копии (старше 7 дней)
        find ${BACKUP_DIR} -name "blog_backup_*.sql.gz" -mtime +7 -delete
        echo "🧹 Старые резервные копии удалены"
        
        echo "📊 Размер резервной копии:"
        ls -lh "${BACKUP_DIR}/${BACKUP_FILE}.gz"
    else
        echo "❌ Ошибка создания резервной копии!"
        exit 1
    fi

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: blog-dev
spec:
  schedule: "0 2 * * *"  # Каждый день в 2:00 UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: postgres:15
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            command:
            - /bin/bash
            - /scripts/backup.sh
            volumeMounts:
            - name: backup-script
              mountPath: /scripts
            - name: backup-storage
              mountPath: /backups
            resources:
              requests:
                memory: 64Mi
                cpu: 50m
              limits:
                memory: 128Mi
                cpu: 100m
          volumes:
          - name: backup-script
            configMap:
              name: backup-script
              defaultMode: 0755
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc
          restartPolicy: OnFailure

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: blog-dev
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi

---
# Ручная job для восстановления из бэкапа
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-restore
  namespace: blog-dev
spec:
  template:
    spec:
      containers:
      - name: postgres-restore
        image: postgres:15
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: BACKUP_FILE
          value: "latest"  # Измените на конкретный файл при необходимости
        command:
        - /bin/bash
        - -c
        - |
          echo "🔄 Начинаем восстановление PostgreSQL..."
          
          if [ "$BACKUP_FILE" = "latest" ]; then
            BACKUP_FILE=$(ls -t /backups/blog_backup_*.sql.gz | head -1)
          else
            BACKUP_FILE="/backups/$BACKUP_FILE"
          fi
          
          echo "📁 Используем файл: $BACKUP_FILE"
          
          if [ ! -f "$BACKUP_FILE" ]; then
            echo "❌ Файл резервной копии не найден!"
            exit 1
          fi
          
          # Распаковываем и восстанавливаем
          gunzip -c "$BACKUP_FILE" | psql -h postgres-service -U postgres -d blog
          
          echo "✅ Восстановление завершено!"
        volumeMounts:
        - name: backup-storage
          mountPath: /backups
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: backup-pvc
      restartPolicy: Never
