apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-blog
  namespace: blog-dev
  labels:
    app: flask-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-blog
  template:
    metadata:
      labels:
        app: flask-blog
    spec:
      containers:
      - name: flask-blog
        image: us-docker.pkg.dev/sonic-harbor-465608-v1/flask-blog/flask-blog:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: blog-secrets
              key: DATABASE_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: blog-secrets
              key: SECRET_KEY
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
      
      # Cloud SQL Proxy sidecar
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.36.0
        command:
          - "/cloud_sql_proxy"
          - "-instances=sonic-harbor-465608-v1:europe-west4:blog-postgres=tcp:5432"
          - "-credential_file=/secrets/cloudsql/credentials.json"
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      
      imagePullSecrets:
      - name: regcred
