apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-blog
  namespace: blog-dev
  labels:
    app: flask-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-blog
  template:
    metadata:
      labels:
        app: flask-blog
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      # Упрощаем security context
      containers:
      - name: flask-blog
        image: europe-west4-docker.pkg.dev/sonic-harbor-465608-v1/blog-flask/blog-flask:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: DATABASE_URL
          value: "sqlite:///blog.db"
        - name: SECRET_KEY
          value: "your-secret-key-here"
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 200m
      # Убираем несуществующий imagePullSecrets
