apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-blog
  namespace: blog-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-blog
  template:
    metadata:
      labels:
        app: flask-blog
    spec:
      containers:
        - name: flask-blog
          image: sttewie/flask-blog:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "development"
            - name: DATABASE_URL
              value: "postgresql://bloguser:blogpassword@127.0.0.1:5432/blogdb"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: SECRET_KEY
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
        - name: cloudsql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.2
          args:
            - "--address=0.0.0.0"
            - "--port=5432"
            - "--credentials-file=/secrets/cloudsql/credentials.json"
            - "sonic-harbor-465608-v1:europe-west4:blog-db"
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
