apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-blog-ingress
  namespace: blog-dev
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  tls:
  - hosts:
    - blog.yourdomain.com
    secretName: flask-blog-tls
  rules:
  # Правило для домена
  - host: blog.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-blog-service
            port:
              number: 80
  # Правило для прямого IP доступа (включая мониторинг)
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-blog-service
            port:
              number: 80
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana-simple-service
            port:
              number: 3000
      - path: /prometheus
        pathType: Prefix
        backend:
          service:
            name: prometheus-simple-service
            port:
              number: 9090
  # Правило для доступа по IP (без host)
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-blog-service
            port:
              number: 80
