apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-blog-ingress
  namespace: blog-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - lapikov.duckdns.org
      secretName: flask-blog-tls
  rules:
    - host: lapikov.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-blog
                port:
                  number: 80
