apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB_NAME}
  namespace: blog-dev
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
      containers:
        - name: migrate
          image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          command: ["bash","-lc","echo 'Starting migration...' && echo 'Waiting for cloud-sql-proxy to be ready...' && until nc -z localhost 5432; do echo 'Waiting for port 5432...'; sleep 2; done && echo 'Database port is open, testing connection...' && python -c 'import psycopg2; conn = psycopg2.connect(\"postgresql://bloguser:blogpassword@localhost:5432/blogdb\"); print(\"Database connection successful\"); conn.close()' && echo 'Running migrations...' && flask db upgrade && echo 'Migration completed successfully'"]
          env:
            - name: FLASK_ENV
              value: "production"
            - name: DATABASE_URL
              value: "postgresql://bloguser:blogpassword@localhost:5432/blogdb"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: blog-secrets
                  key: SECRET_KEY
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4
          args:
            - "--port=5432"
            - "--credentials-file=/secrets/credentials.json"
            - "--verbose"
            - "sonic-harbor-465608-v1:europe-west4:blog-db"
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
