apiVersion: v1
kind: Service
metadata:
  name: flask-blog-service
  namespace: blog-dev
  labels:
    app: flask-blog
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: flask-blog
