apiVersion: v1
kind: Service
metadata:
  name: flask-blog
  namespace: blog-dev
spec:
  selector:
    app: flask-blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
