# /home/gcpa4607/blog-flask/blog-flask-prod/docker-compose.prod.yml
# Финальная, рабочая версия для продакшена

# Атрибут "version" устарел, поэтому убираем его, как советует Docker
services:
  db:
    image: postgres:15
    restart: always
    env_file: .env # Указываем, что переменные для DB берутся из .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - blog-network

  web:
    image: sttewie/flask-blog:latest # Ваш образ из Docker Hub
    restart: always
    env_file: .env # Указываем, что переменные для Web берутся из .env
    depends_on:
      - db
    networks:
      - blog-network

  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - blog-network
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    # У сервиса certbot нет своей конфигурации, кроме томов
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

networks:
  blog-network:
    driver: bridge

volumes:
  pgdata: