version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env.prod     # ← сюда!
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - blog-network

  web:
    image: sttewie/flask-blog:latest
    restart: always
    env_file:
      - .env.prod     # ← сюда!
    environment:
      FLASK_ENV: production
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  pgdata:
