# blog-flask-prod/docker-compose.init.yml
version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx/nginx.init.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot