version: '3.8'

# Подхватываем переменные окружения из файла .env.prod
env_file:
  - .env.prod

services:
  db:
    image: postgres:15
    restart: always
    environment:
      # Параметры берутся из .env.prod
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - blog-network

  web:
    image: sttewie/flask-blog:latest
    restart: always
    environment:
      # Приложение будет брать DATABASE_URL и SECRET_KEY из .env.prod
      FLASK_ENV: production
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db
    # Меняем порт с 80:5000 на 5000:5000,
    # чтобы контейнер не «захватывал» 80 – он уже занят Nginx на хосте
    ports:
      - "5000:5000"
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  pgdata:
