apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-blog
  namespace: blog-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-blog
  template:
    metadata:
      labels:
        app: flask-blog
    spec:
      containers:
        - name: flask-blog
          image: sttewie/flask-blog:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "development"
            - name: DATABASE_URL
              value: "postgresql://bloguser:blogpassword@34.32.203.226:5432/blogdb"
            - name: SECRET_KEY
              value: "your_secret_key"
